version: "2"

formatters:
  enable:
    - gofumpt
    - goimports

linters:
  # Default linters (errcheck, govet, ineffassign, staticcheck, unused)
  # are always enabled. Add extras here.
  enable:
    - errorlint
    - misspell
    - gocritic
    - revive
    - unconvert
    - unparam
  settings:
    errcheck:
      # CLI output to stdout/stderr — writes that fail are not recoverable.
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    misspell:
      locale: US
  exclusions:
    rules:
      # "api" is descriptive enough under internal/api.
      - path: "internal/api"
        linters: [revive]
        text: "avoid meaningless package names"

issues:
  # Show all issues, don't limit per-linter.
  max-issues-per-linter: 0
  max-same-issues: 0
